# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
python:
  - "3.6"
install:
  - pip install --upgrade setuptools pip
  - pip install pipenv
  - pipenv install --dev
  - pipenv install --dev tox-travis
script:
  - pipenv run tox
